<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomePageController::index'], [], [['text', '/']], [], [], []],
    'app_home_page' => [[], ['_controller' => 'App\\Controller\\HomePageController::homePage'], [], [['text', '/home/page']], [], [], []],
    'App\Controller\HomePageController::index' => [[], ['_controller' => 'App\\Controller\\HomePageController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\HomePageController::homePage' => [[], ['_controller' => 'App\\Controller\\HomePageController::homePage'], [], [['text', '/home/page']], [], [], []],
];
